package;

/*
LIST OF DO NOT TOUCH:
    CAMERA SINGING MOVEMENT
    OPTIONS THAT I MADE
    IMPORTANT STUFF LIKE SOME THINGS IN PROJECT.XML
    THE NOTE CODE
    THE NOTE SPLASH CODE
DO NOT TOUCH (MODIFY) ANYTHING FROM THESE, THE GAME WILL BROKE
*/